- hosts: all
  user: vagrant
  sudo: yes
  vars_files:
    - vars/main.yml
  roles:
    - common
    - imagemagick
    - nodejs
    - chruby
    - ruby-install
    - postgresql
    - phantomjs
    - redis
    - memcached
