---
- name: downloading package {{version}}
  get_url:
    url: https://github.com/postmodern/chruby/archive/v{{version}}.tar.gz
    dest: /tmp/chruby-{{version}}.tar.gz
    force: no

- name: unarchiving the package
  unarchive: >
    src=/tmp/chruby-{{version}}.tar.gz
    dest=/tmp/
    creates=/tmp/chruby-{{version}}
    copy=no

- name: installing package
  sudo: yes
  command: make install chdir=/tmp/chruby-{{version}} creates=/usr/local/share/chruby/chruby.sh

- name: profile.d {{version}}
  sudo: yes
  copy:
    src: chruby.sh
    dest: /etc/profile.d/chruby.sh
    owner: root
    group: root
    mode: 0744

- name: setting default to ruby {{ruby_version}}
  shell: echo "{{ruby_version}}" > /home/{{ansible_ssh_user}}/.ruby-version
  when: ruby_version is defined
