---
- name: adding nodejs repository
  apt_repository: >
    repo='deb https://deb.nodesource.com/node trusty main'
    state=present

- name: adding nodejs repository key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: installing nodejs package
  apt: >
    pkg=nodejs
    force=yes
    state=latest
    update_cache=yes
